/// Sum of total Reportable Accidents
table _Measure_Table
	lineageTag: ce2aa14d-6693-4b71-be30-f49cd138f021

	/// Refresh Date for Loss Run Report
	measure 'Report Refresh Date' = "Report as of: " & Max('zLast Refresh Datetime'[Last Refresh Datetime])
		displayFolder: _Metadata
		lineageTag: 2360455c-966c-4ea4-af74-a5137572a971

	measure Sales = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    FILTER(
			        'F_Shipper_Item',
			        'F_Shipper_Item'[SALES_POSTED_DATE] < EOMONTH(TODAY(), -1) + 1
			    )
			)
			
			```
		formatString: \$#,0;(\$#,0);\$#,0
		lineageTag: e3127b64-1e01-404b-9835-0c9f50279ded

	measure Sales_to_Date = ```
			CALCULATE(
			    [Sales_Raw],
			    DATESYTD('F_Shipper_Item'[SALES_POSTED_DATE])
			    )
			
			
			```
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 986cd868-8b47-4407-a263-8ebb36a92c57

	measure _Objective_Count = ```
			
			CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective"
			    )
			```
		formatString: 0
		lineageTag: 46aa87ae-1e65-480d-8477-691b91ca271b

	measure Objective_Count_Committed_Current_PI = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details'[Committed Objective] = TRUE(),
			    'Delivery_Details'[PI] = CurrentPIValue
			    )
			
			```
		formatString: 0
		lineageTag: 16479954-d2d7-4e6f-869f-5878c6993438

	measure _Objective_Count_Uncommitted = ```
			
			VAR CountResult = CALCULATE(
			    DISTINCTCOUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    KEEPFILTERS('Delivery_Details_New'[Committed Objective] = FALSE()),
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3
			    )
			RETURN
			    IF(CountResult = 0, "0", CountResult)
			```
		formatString: 0
		lineageTag: 839dd493-36ff-4a0b-9352-619792dea7c3

	measure Objective_Count_On_Track = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details'[Committed Objective] = TRUE(),
			    'Delivery_Details'[PI] = CurrentPIValue,
			    NOT(CONTAINSSTRING('Delivery_Details'[Tags], "At Risk"))
			    )
			```
		formatString: 0
		lineageTag: 3e5aa05d-3913-4f28-90c4-2eda11dcff12

	measure Objective_Count_At_Risk =
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult =
			    CALCULATE(
			        COUNT('Delivery_Details'[Work Item Id]),
			        'Delivery_Details'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details'[Committed Objective] = TRUE(),
			        'Delivery_Details'[PI] = CurrentPIValue,
			        CONTAINSSTRING('Delivery_Details'[Tags], "At Risk")
			    )
			RETURN
			IF(CountResult = 0, "0", CountResult)
		formatString: 0
		lineageTag: 79ce480f-6773-40a3-b2d3-5d3ce7342443

	measure PI_Current = ```
			
			CALCULATE(
			    [PI_Calculated], 
			    '_Date_Table'[Date] = TODAY()
			)
			```
		formatString: 0
		lineageTag: dcaecd45-d2e7-4669-8834-397250ee91fc

	measure Sales_Growth_YoY_Table = ```
			
			VAR CurrentYear = YEAR(TODAY())
			VAR CurrentYearSales = [Sales_YTD_AsOfToday]
			VAR PriorYear = CALCULATE(
			    [Sales_YTD_AsOfToday],
			    SAMEPERIODLASTYEAR('_Date_Table'[Date])
			)
			VAR PctChange = DIVIDE((CurrentYearSales - PriorYear), PriorYear)
			RETURN
			    IF(ISBLANK(PctChange), "", PctChange)
			
			```
		lineageTag: 18fb5d57-d02f-47bd-a0cb-abc2ee4f49be

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Prior_Year =
			CALCULATE(
			    [Sales_to_Date],
			    DATEADD('F_Shipper_Item'[SALES_POSTED_DATE], -1, YEAR)
			    )
		lineageTag: 884c18ca-ea06-40e7-95d1-9bfe591b68e9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Digital = ```
			CALCULATE(
			    [Sales], 
			    'F_Shipper_Item'[WEB_ORDERS] = "Web Sales"
			)
			```
		lineageTag: 078b2c14-e710-42a1-9e5e-4dc068e33b37

	measure Sales_Digital_Prior_Year =
			CALCULATE(
			    [Sales_Digital_to_Date],
			    DATEADD('F_Shipper_Item'[SALES_POSTED_DATE], -1, YEAR)
			    )
		lineageTag: 65ddfde0-7339-48a5-acc5-b6f4a1b72a6e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Growth_YoY_Digital_Card = ```
			
			VAR CurrentYear = YEAR(TODAY())
			VAR CurrentYearSales = 
			    CALCULATE(
			        [Sales_YTD_AsOfToday_Digital],
			        '_Date_Table'[Year] = CurrentYear
			    )
			VAR PriorYearSales = 
			    CALCULATE(
			        [Sales_YTD_AsOfToday_Digital],
			        '_Date_Table'[Year] = CurrentYear - 1
			    )
			RETURN
			IF(
			    NOT(ISBLANK(PriorYearSales)),
			    DIVIDE(
			        (CurrentYearSales - PriorYearSales),
			        PriorYearSales,
			        BLANK()
			    ),
			    BLANK()
			)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ab2957cf-7b9e-4c0b-bf50-5f94fe3a2970

	measure PI_Calculated = ```
			
			VAR CurrentDate = MAX(D_Calendar[CALENDAR_DATE])
			VAR PI1Start = DATE(2023, 11, 9)
			VAR PI2Start = DATE(2024, 3, 21)
			VAR PI3Start = DATE(2024, 6, 20) 
			VAR PI4Start = DATE(2024, 9, 18)  
			VAR PI5Start = DATE(2024, 12, 12)  
			VAR PI6Start = DATE(2025, 3, 6)
			RETURN
			SWITCH(
			    TRUE(),
			    CurrentDate >= PI6Start, 6,
			    CurrentDate >= PI5Start, 5,
			    CurrentDate >= PI4Start, 4,
			    CurrentDate >= PI3Start, 3,
			    CurrentDate >= PI2Start, 2,
			    CurrentDate >= PI1Start, 1,
			    BLANK()
			)
			
			```
		formatString: 0
		lineageTag: cd996566-de17-49e0-9b7d-dfa4d427f13d

	measure _Objective_Count_Committed = ```
			
			CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    KEEPFILTERS('Delivery_Details_New'[Committed Objective] = TRUE()),
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3
			    )
			```
		formatString: 0
		lineageTag: 425ff0b7-ca13-4a7c-acfe-15afadea0fa0

	measure Objective_Count_Committed_Previous_PIs = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			IF(
			    MAX('Delivery_Details'[PI]) >= CurrentPIValue,
			    BLANK(),
			    CALCULATE(
			        COUNT('Delivery_Details'[Work Item Id]), 
			        'Delivery_Details'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details'[Committed Objective] = TRUE()
			        )
			    )
			```
		formatString: 0
		lineageTag: 4584e300-e77b-4293-9eed-beb6045716de

	measure Objective_Count_Uncommitted_Previous_PIs = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			IF(
			    MAX('Delivery_Details'[PI]) >= CurrentPIValue,
			    BLANK(),
			    CALCULATE(
			        COUNT('Delivery_Details'[Work Item Id]), 
			        'Delivery_Details'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details'[Committed Objective] = FALSE()
			        )
			    )
			```
		formatString: 0
		lineageTag: 67cae43b-f3dd-46be-b577-61497ac57607

	measure Objective_Count_Uncommitted_Current_PI = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details'[Committed Objective] = FALSE(),
			    'Delivery_Details'[PI] = CurrentPIValue
			    )
			```
		formatString: 0
		lineageTag: a80e67f9-794c-414f-9cce-909c379a6caa

	measure Predictability_Previous = ```
			
			VAR PreviousPI = [PI_Previous] 
			VAR PredictabilityLastPI = CALCULATE(
			    SUM('APMO_Predictability_COPY_Unpivoted'[Value]),
			    'APMO_Predictability_COPY_Unpivoted'[Attribute] = "ART Predictability Score",
			    'APMO_Predictability_COPY_Unpivoted'[PI] = PreviousPI
			    )
			RETURN
			    IF(ISBLANK(PredictabilityLastPI), "", PredictabilityLastPI)
			```
		formatString: 0%;-0%;0%
		lineageTag: 1b9beece-7b35-4762-8341-c1c6ce3842d0

	measure Predictability_Business_Value = ```
			
			CALCULATE(
			    SUM(APMO_Predictability_COPY_Unpivoted[Value]), 
			    APMO_Predictability_COPY_Unpivoted[Attribute] = "Business Value  (Committed)"
			)
			```
		formatString: 0
		lineageTag: 2917984a-6fa6-4fb4-a635-beec99ced2df

	measure Predictability_Actual_Value = ```
			
			CALCULATE(
			    SUM(APMO_Predictability_COPY_Unpivoted[Value]), 
			    APMO_Predictability_COPY_Unpivoted[Attribute] = "Actual Business Value"
			)
			```
		formatString: 0
		lineageTag: 238ce548-c2c2-484f-9809-284c53f3aa78

	measure Sales_Digital_to_Date =
			CALCULATE(
			    [Sales_Digital],
			    DATESYTD('F_Shipper_Item'[SALES_POSTED_DATE])
			    )
		lineageTag: 2978f8cc-6221-45aa-8bed-7c9c68c658bf

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Placeholder_Cost_to_Serve = "Return on Sales"
		lineageTag: 826a4869-8731-4777-830c-196c8d8ff6ef

	measure Placeholder_On_Time_Fulfillment = "On-Time Fulfillment"
		lineageTag: 29d8b707-c953-4eb2-8585-ed2416a73403

	measure Placeholder_Acquisition_Synergy = "Acquisition Synergy Realization"
		lineageTag: bdde215a-b2a1-4cb7-b9ef-226e7604e08e

	measure Placeholder_Competitor_Sales_Growth = "Competitor Sales Growth"
		lineageTag: 5da60015-0228-4378-af09-a080f66cf42e

	measure Placeholder_Employee_Engagement = "Employee Engagement"
		lineageTag: 3ca7f450-748a-46af-bb5e-9188b9e2eb1d

	measure Placeholder_IT_Employee_Retention = "IT Employee Retention"
		lineageTag: f359e479-ad7c-468d-95d7-b012f1ba2455

	measure Placeholder_Aggregated_DORA_Score = "87"
		lineageTag: 2b205168-f689-4c08-a9c4-838a54213aa4

	measure Employee_Engagement = "86%"
		lineageTag: ae2b0f99-63f9-4bf2-a46c-a3bde6c8586f

	measure Predictability_APMO_COPY_PI_3 = ```
			CALCULATE(
			    SUM('APMO_Predictability_COPY'[ART Predictability Score]),
			    'APMO_Predictability_COPY'[PI] = 3
			    ) 
			
			```
		formatString: 0%;-0%;0%
		lineageTag: aad8cda5-aabc-4cda-ba73-9e8f5ed14569

	measure PI_Previous = [PI_Current] - 1
		formatString: 0
		lineageTag: d3907d26-1262-42ef-9f65-7073a89ddd1b

	measure Predictability_APMO_COPY_PI_2 =
			CALCULATE(
			    SUM('APMO_Predictability_COPY'[ART Predictability Score]),
			    'APMO_Predictability_COPY'[PI] = 2
			    )
		formatString: 0%;-0%;0%
		lineageTag: 2a51ebbb-b15b-4f45-a4c3-70d48d5c8e08

	measure Predictability_APMO_COPY_Difference =
			
			VAR Difference = ([Predictability_Previous] - [Predictability_Previous_Previous]) * 100
			RETURN
			 IF(ISBLANK(Difference), "", Difference)
		formatString: 0
		lineageTag: 1b52aca0-4a20-4a74-838e-4ad2f31553c8

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Objective_Count_Committed_Current_vs_Previous = [Objective_Count_Committed_Current_PI] - [Objective_Count_Committed_Previous_PI]
		formatString: 0
		lineageTag: b9e525b4-f0ca-48e7-ba01-c81ed8ec869c

	measure Objective_Count_Committed_Previous_PI = ```
			
			VAR CurrentPIValue = [PI_Current] - 1
			RETURN
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details'[Committed Objective] = TRUE(),
			    'Delivery_Details'[PI] = CurrentPIValue
			    )
			```
		formatString: 0
		lineageTag: dcd74fba-82b7-4850-87f8-1b43ee8ff986

	measure Text_Change_in_Predictability = "pp vs. PI " & FORMAT([PI_Previous_Previous], "0")
		lineageTag: 3dd8e486-1479-4fb7-8de9-470f97a3c4a2

	measure PI_Previous_Previous = [PI_Current] - 2
		formatString: 0
		lineageTag: 175cc63e-8271-4058-8b8b-51ecea74b89c

	measure Text_Change_in_Objectives = "+/- vs. PI " & FORMAT([PI_Previous], "0")
		lineageTag: 51859525-4e12-4189-9e8a-3ecc98e7f4d7

	measure Objective_Count_Uncommitted_Previous_PI = ```
			
			VAR CurrentPIValue = [PI_Current] - 1
			RETURN
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details'[Committed Objective] = FALSE(),
			    'Delivery_Details'[PI] = CurrentPIValue
			    )
			```
		formatString: 0
		lineageTag: e8851aa2-fd31-4a63-b235-d3a7e815a4a6

	measure Objective_Count_Uncommitted_Current_vs_Previous = [Objective_Count_Uncommitted_Current_PI] - [Objective_Count_Uncommitted_Previous_PI]
		formatString: 0
		lineageTag: 5d16c8b7-6a87-4bcd-913d-a4fc7b14be75

	measure Text_Current_PI = "PI " & FORMAT([PI_Current], "0")
		lineageTag: 2a54ad83-fa03-44c2-9d50-5335694d26f5

	measure Placeholder_Value_Quadrant = "Value Quadrant"
		lineageTag: d3e20af7-c05b-4ace-931c-688859c4a85d

	measure Placeholder_Plan_v_Actual_Closed = "Plan vs. Actual Closed"
		lineageTag: 2d277da1-ca45-408a-aa3b-c9c905a84781

	measure Predictability_APMO_COPY_Previous_PIs = ```
			
			VAR CurrentPIValue = [PI_Current]
			RETURN
			IF(
			    MAX('APMO_Predictability_COPY'[PI]) >= CurrentPIValue,
			    BLANK(),
			    CALCULATE(
			        MAX('APMO_Predictability_COPY'[ART Predictability Score]) 
			        )
			    )
			```
		formatString: 0%;-0%;0%
		lineageTag: 80a95537-920b-4421-be56-4959f062c785

	measure Placeholder_Objective_Breakdown = "Objective Breakdown"
		lineageTag: 94283903-3c0c-4e05-89bc-fae11f9c5ca5

	measure _Objective_Count_Delivered_On_Plan = ```
			
			VAR CurrentPI = [PI_Current]
			RETURN
			    CALCULATE(
			        COUNT('Delivery_Details_New'[Work Item Id]), 
			        'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3, 
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] < CurrentPI,
			        KEEPFILTERS('Delivery_Details_New'[Committed Objective] = TRUE()),
			        'Delivery_Details_New'[State] = "Closed",
			        NOT(CONTAINSSTRING('Delivery_Details_New'[Iteration Path], "Incomplete"))
			    )
			```
		formatString: 0
		lineageTag: dfef4db2-71ce-402b-a3bd-7e09896064bc

	measure Objective_Count_Delivered_Late =
			
			CALCULATE(
			    [_Objective_Count],
			    'Delivery_Details'[Committed Objective] = TRUE(),
			    'Delivery_Details'[State] = "Closed",
			    'Delivery_Details'[Committed_PI] < 'Delivery_Details'[Closed_PI]
			)
		formatString: 0
		lineageTag: ff097456-c223-4c1d-9724-bb06b656af0c

	measure _Objective_Count_Missed = ```
			
			    CALCULATE(
			        [_Objective_Count_Committed],
			        'Delivery_Details_New'[State] = "Closed",
			        CONTAINSSTRING('Delivery_Details_New'[Iteration Path], "Incomplete") 
			    )
			
			```
		formatString: 0
		lineageTag: 9bb70820-5373-4edb-90a8-41a13231d441

	measure Operational_Return =
			
			VAR Calc = AVERAGE(Return_On_Sales[RoS])
			RETURN
			    IF(ISBLANK(Calc), "", Calc)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: ad2ce3c1-57b5-4c4d-a488-9acc3c022dd1

	measure Text_Change_in_Employee_Engagement = -0.03
		formatString: 0%;-0%;0%
		lineageTag: 986414d2-dd01-4af2-b50d-328cb3b15354

	measure Text_vs_Previous_Year = ```
			"vs. PY" 
			```
		lineageTag: 2d4328d1-3782-47d9-8f5d-9cb43bedc0d6

	measure Costs =
			
			CALCULATE(
			    SUM('F_Shipper_Item'[TOTAL_CUSTOMER_COST_AMOUNT]),
			    FILTER(
			        'F_Shipper_Item',
			        'F_Shipper_Item'[SALES_POSTED_DATE] < EOMONTH(TODAY(), -1) + 1
			    )
			)
		lineageTag: 8c254c76-9f08-4205-99fc-56cff9762d2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Costs_to_Date =
			CALCULATE(
			    [Costs_Raw],
			    DATESYTD('F_Shipper_Item'[SALES_POSTED_DATE])
			    )
		formatString: \$#,0.0;(\$#,0.0);\$#,0.0
		lineageTag: 9b2f3c8e-6da7-4218-932d-19355275ab2c

	measure DORA_Frequency = [Story Measure] + [Bug Measure] + [PIR Measure]
		formatString: 0
		lineageTag: d209868a-8025-4c75-ba47-73f56733537a

	measure Frequency_Delivery_Details =
			
			VAR BugCount = CALCULATE(
			    COUNT(Delivery_Details[Work Item Id]),
			    Delivery_Details[Work Item Type] = "Bug"
			)
			VAR PIRCount = CALCULATE(
			    COUNT(Delivery_Details[Work Item Id]),
			    Delivery_Details[Work Item Type] = "PIR"
			)
			VAR UserStoryCount = CALCULATE(
			    COUNT(Delivery_Details[Work Item Id]),
			    Delivery_Details[Work Item Type] = "User Story"
			)
			RETURN
			  BugCount + PIRCount + UserStoryCount
		formatString: 0
		lineageTag: 280c4b84-5007-47fc-9f50-2705db71f0cd

	measure 'DORA_Failure_Rate (CFRP Measure)' =
			
			VAR BugCount = CALCULATE(
			    COUNT(Append1[WorkItemId]),
			    Append1[WorkItemType] = "Bug"
			)
			VAR PIRCount = CALCULATE(
			    COUNT(Append1[WorkItemId]),
			    Append1[WorkItemType] = "PIR"
			)
			RETURN
			    DIVIDE(BugCount, PIRCount)
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 09882ed7-a27a-4c0e-895c-14cd3d8b7a03

	measure DORA_Bug_Count =
			CALCULATE(
			    COUNT(Append1[WorkItemId]),
			    Append1[WorkItemType] = "Bug"
			)
		formatString: 0
		lineageTag: fcdfa6dd-58bc-4844-ba2c-e703d2577834

	measure DORA_PIR_Count =
			CALCULATE(
			    COUNT(Append1[WorkItemId]),
			    Append1[WorkItemType] = "PIR"
			)
		formatString: 0
		lineageTag: 31c6046f-5777-4fa6-ae76-f4cbfbc6abf8

	measure 'DORA_Lead_Time (ActivetoClosed)' = ```
			DATEDIFF(AVERAGE(Stories[ActivatedDate]),MAX(PIRStories[ClosedDate]),DAY)
			
			```
		formatString: 0
		lineageTag: 660e0728-8056-4f9a-847f-d9b51ce0be91

	measure Employee_Starting_Count = ```
			
			VAR CurrentYear = YEAR(MAX('_Date_Table'[Date]))
			RETURN
			CALCULATE(
			    COUNTROWS(D_Employee),
			    FILTER(
			        D_Employee,
			        VALUE(D_Employee[DATE_HIRED]) < DATE(CurrentYear, 1, 1)
			        && (VALUE(D_Employee[DATE_TERMINATED]) = DATE(1900, 1, 1) 
			            || VALUE(D_Employee[DATE_TERMINATED]) >= DATE(CurrentYear, 1, 1))
			    )
			)
			
			```
		formatString: 0
		lineageTag: 07ce3e67-efa3-469f-91c0-fad05eb9c181

	measure Employee_Count_New_Hires_Current_Year = ```
			
			VAR OneYearAgo = EDATE(MAX(_Date_Table[Date]), -12)
			RETURN
			CALCULATE(
			    COUNTROWS(D_Employee),
			    D_Employee[DATE_HIRED] > OneYearAgo,
			    CONTAINSSTRING(D_Employee[EMP_DEPT], "DP")
			)
			
			
			```
		formatString: 0
		lineageTag: 2d5e61ca-5a05-400e-9e65-bc236d9f7a28

	measure Employee_Count_Exits_Past_Year = ```
			
			VAR OneYearAgo = EDATE(MAX(_Date_Table[Date]), -12)
			VAR CurrentDate = MAX(_Date_Table[Date])
			RETURN
			CALCULATE(
			    COUNTROWS(D_Employee),
			    D_Employee[DATE_TERMINATED] > OneYearAgo,
			    D_Employee[DATE_TERMINATED] <= CurrentDate,
			    D_Employee[DATE_TERMINATED] <> DATE(1900,1,1),
			    CONTAINSSTRING(D_Employee[EMP_DEPT], "DP")
			)
			
			
			```
		formatString: 0
		lineageTag: 539c09a9-d3a3-4211-815f-af73bc07803c

	measure Employee_Count_Total_Active_IT = ```
			
			CALCULATE(
			    DISTINCTCOUNT(D_Employee[EMPLOYEE_ID]),
			    CONTAINSSTRING(D_Employee[EMP_DEPT], "DP"),
			    D_Employee[DATE_TERMINATED] = DATE(1900, 1, 1)
			)
			    
			
			```
		formatString: 0
		lineageTag: 3deaa1ef-1a9f-4bd1-84d5-fbcb54a3f108

	measure Employee_Count_One_Year_Ago = ```
			
			VAR OneYearAgo = EDATE(MAX(_Date_Table[Date]), -12)
			RETURN
			CALCULATE(
			    DISTINCTCOUNT(D_Employee[EMPLOYEE_ID]),
			    CONTAINSSTRING(D_Employee[EMP_DEPT], "DP"),
			    D_Employee[DATE_HIRED] <= OneYearAgo,                          // Hired on or before one year ago
			    D_Employee[DATE_TERMINATED] > OneYearAgo                       // Still employed one year ago
			        || D_Employee[DATE_TERMINATED] = DATE(1900,1,1)            // Or date placeheld with placeholder 
			)
			
			
			```
		formatString: 0
		lineageTag: b45eff6b-70b5-46af-826d-0b0305543cfa

	measure test_OneYearAgo = EDATE(MAX(_Date_Table[Date]), -12)
		formatString: General Date
		lineageTag: b7425390-9c96-47b8-b341-cf76e344443d

	measure Employee_Waterfall =
			
			SWITCH(
			    SELECTEDVALUE(IT_Employee_Retention[Category]),
			     "Previous Year Count", [Employee_Count_One_Year_Ago],
			     "New Hires", [Employee_Count_New_Hires_Current_Year],
			     "Exits", -[Employee_Count_Exits_Past_Year]//,
			     //"Employee_Count_Current", [Employee_Count_Total_Active_IT]
			)
		formatString: 0
		lineageTag: 1058e4a4-d2ed-4747-b11c-984c2e6c6d63

	measure Employee_Retention_Rate = ```
			
			VAR IntitialEmployees = [Employee_Count_One_Year_Ago]
			VAR RemainingEmployees = [Employee_Count_One_Year_Ago] - [Employee_Count_Exits_Past_Year]
			VAR DivideEmployees = DIVIDE(RemainingEmployees, IntitialEmployees)
			RETURN
			  IF(ISBLANK(DivideEmployees), "", DivideEmployees)   
			
			```
		formatString: 0%;-0%;0%
		lineageTag: 9caa6d85-d33d-4bac-be98-c40d0907a623

	measure MTTR = DATEDIFF(CALCULATE(MIN(Bugs[CreatedDate]),Bugs[Severity]="2 - High"),MAX(PIR[ClosedDate]),DAY)
		formatString: 0
		lineageTag: 495eb503-88bb-4c07-b6a7-34eff579fc57

	measure 'S1-2 MTTR' = ```
			CALCULATE(
			    DATEDIFF(  
			        MIN(Bugs[CreatedDate]),  
			        MAX(PIR[ClosedDate]),
			        HOUR
			        ),
			    Bugs[Severity]="1 - Critical"
			    ) / 24
			
			```
		formatString: 0
		lineageTag: f63ec400-21c3-4325-b15f-1ea49d42c9ff

	measure 'Avg. MTTR' = AVERAGEX(VALUES(PIR[ClosedDate]), [MTTR])
		lineageTag: 1d0db215-c345-499c-ab5f-0589a716b45b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Avg. S1-2 MTTR' = ```
			ABS(AVERAGEX(VALUES(PIR[ClosedDate]), [S1-2 MTTR])) 
			```
		formatString: 0.000
		lineageTag: 76062dab-839b-4340-934c-47ec75d0dc7c

	measure 'Bug Measure' = CALCULATE( COUNT(Append1[WorkItemType]), Append1[WorkItemType] = "Bug" )
		formatString: 0
		lineageTag: c91a0503-88c0-47db-b4a5-2d406af019a8

	measure 'PIR Measure' = CALCULATE( COUNT(Append1[WorkItemType]), Append1[WorkItemType] = "PIR" )
		formatString: 0
		lineageTag: c02ed6d9-2f46-4d74-9f2f-f9955b8e88c4

	measure 'Story Measure' = CALCULATE( COUNT(Append1[WorkItemType]), Append1[WorkItemType] = "User Story" )
		formatString: 0
		lineageTag: 6f504cdc-5a92-4eb2-9c1f-abcf600e9a30

	measure 'CFRP Measure' = DIVIDE( [Bug Measure], [PIR Measure] )
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: b3085980-bb38-48e9-8071-46e0a4da9f6e

	measure ActiveToClosed = DATEDIFF(AVERAGE(Stories[ActivatedDate]),MAX(PIRStories[ClosedDate]),DAY)
		formatString: 0
		lineageTag: dbfc2cb0-486e-40c2-b6d2-1e66374a869d

	measure CreatedToClosed = DATEDIFF(AVERAGE(Stories[CreatedDate]),MAX(PIRStories[ClosedDate]),DAY)
		formatString: 0
		lineageTag: b43fa894-927f-4d7e-a0ae-206bb49832c0

	measure test_OneYearAgo2 = EDATE(MAX(_Date_Table[Date]), -12)
		formatString: General Date
		lineageTag: a26efd2b-9537-4b0f-896c-3aa4ddf3b38d

	measure Difference = [CreatedToClosed] - [ActiveToClosed]
		formatString: 0
		lineageTag: f6ea1923-f5d3-473a-94c8-9ff89ea018d2

	measure _Objective_Count_Committed_Current_PI = ```
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult = CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]),
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    KEEPFILTERS('Delivery_Details_New'[Committed Objective] = TRUE()),
			    KEEPFILTERS('Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue)
			)
			RETURN
			    IF(ISBLANK(CountResult), "", CountResult)
			
			```
		formatString: 0
		lineageTag: c258a171-6d11-4d5d-b4c3-07a3257dea75

	measure _Objective_Count_Uncommitted_Current_PI = ```
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult = 
			CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    KEEPFILTERS('Delivery_Details_New'[Committed Objective] = FALSE()),
			    KEEPFILTERS('Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue),
			    KEEPFILTERS(ALLSELECTED('Delivery_Details_New'[Risk])) -- Ensure Risk is considered
			)
			RETURN
			    IF(CountResult = 0, "", CountResult)
			
			```
		formatString: 0
		lineageTag: e47bc56f-05ec-4cb7-b6ea-55863ffc3c49

	measure _Objective_Count_On_Track_Current_PI = ```
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult = 
			    CALCULATE(
			        COUNT('Delivery_Details_New'[Work Item Id]), 
			        'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			        KEEPFILTERS('Delivery_Details_New'[Committed Objective] = TRUE()),
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue,
			        KEEPFILTERS(NOT('Delivery_Details_New'[Risk] IN {"Red", "Yellow"}))
			    )
			RETURN
			    IF(ISBLANK(CountResult), " ", CountResult)
			
			```
		formatString: 0
		lineageTag: 04d9fb25-3192-4905-bc41-8697cd996177

	measure _Objective_Count_At_Risk_Current_PI =
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult =
			    CALCULATE(
			        COUNT('Delivery_Details_New'[Work Item Id]),
			        'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			        KEEPFILTERS('Delivery_Details_New'[Committed Objective] = TRUE()),
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue,
			        KEEPFILTERS('Delivery_Details_New'[Risk] IN {"Red", "Yellow"})
			    )
			RETURN
			    IF(ISBLANK(CountResult), " ", CountResult)
		formatString: 0
		lineageTag: 89948b80-4cb3-4497-8bed-b3d5af0fc6a4

	measure _Objective_Count_Committed_Previous_PI = ```
			
			VAR CurrentPIValue = [PI_Current] - 1
			VAR CountResult = CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[Committed Objective] = TRUE(),
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue
			    )
			RETURN
			    IF(ISBLANK(CountResult), "", CountResult)
			```
		formatString: 0
		lineageTag: 7c8c4d24-37b6-4bae-8f95-39bf3eb594de

	measure _Objective_Count_Committed_Current_vs_Previous = ```
			
			VAR Crnt = [_Objective_Count_Committed_Current_PI] 
			VAR Previous = [_Objective_Count_Committed_Previous_PI]
			VAR Diff = IF(Crnt = "" || Previous = "", "", Crnt - Previous)
			RETURN
			  Diff
			```
		formatString: 0
		lineageTag: caf50b80-12cb-4d99-8797-3a7d8a4a9c91

	measure _Objective_Count_Uncommitted_Previous_PI = ```
			
			VAR CurrentPIValue = [PI_Current] - 1
			Var CountResult = 
			CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[Committed Objective] = FALSE(),
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue
			    )
			RETURN
			    IF(CountResult = 0, "", CountResult)
			```
		formatString: 0
		lineageTag: 5455d9c1-1545-4674-b0a4-6fa3767dbc07

	measure _Objective_Count_Uncommitted_Current_vs_Previous =
			
			VAR Crnt = [_Objective_Count_Uncommitted_Current_PI]
			VAR Previous = [_Objective_Count_Uncommitted_Previous_PI]
			VAR Diff = IF(Crnt = "" || Previous = "", "", Crnt - Previous)
			RETURN
			  Diff
		formatString: 0
		lineageTag: 15c3cfed-9ad4-4914-80ac-3f9ba0fcd9a0

	measure 'Line Count' = DISTINCTCOUNT(F_Order_Item[ORD_LN_KEY])
		formatString: 0
		lineageTag: 2f8005dc-f877-4721-8637-92dd7755d05c

	measure 'Late Lines' = COUNTROWS(FILTER(F_Order_Item, F_Order_Item[LATE_LINE] = "Yes"))
		formatString: 0
		lineageTag: 82f4b2d3-335d-4c04-89f6-4bd29bbe7f4e

	measure 'Late Lines %' = ```
			
			VAR DivideLines = DIVIDE([Late Lines], [Line Count])
			RETURN
			    IF(ISBLANK(DivideLines), "", DivideLines)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: bfb664b8-9f0b-424b-a477-21b4f2ea24cd

	measure Sales_YTD_AsOfToday = ```
			
			VAR CurrentMonth = MONTH(TODAY()) 
			VAR CurrentDay = DAY(TODAY())
			VAR CurrentYear = YEAR(TODAY())
			VAR Sales = CALCULATE( 
			    [Sales], 
			    FILTER( 
			        '_Date_Table',  
			        MONTH('_Date_Table'[Date]) <= CurrentMonth && 
			        DAY('_Date_Table'[Date]) <= CurrentDay &&
			        IF(
			            HASONEVALUE('_Date_Table'[Year]),
			            TRUE(),
			            YEAR('_Date_Table'[Date]) = CurrentYear
			        )
			    ) 
			) 
			RETURN 
			    IF(ISBLANK(Sales), BLANK(), Sales)
			
			```
		lineageTag: a16fb9d4-3273-4a98-8f18-65f1847d989e

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure test_prior_year =
			
			CALCULATE(
			    [Sales],
			    SAMEPERIODLASTYEAR('_Date_Table'[Date])
			)
		lineageTag: e968aada-0427-40ee-b941-dce3b571500c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YoY = ```
			CALCULATE(
			    [Sales], 
			    SAMEPERIODLASTYEAR(_Date_Table[Date])
			)
			
			```
		formatString: 0
		lineageTag: adceffb7-ecfb-4680-93c0-d95516e1daf4

		annotation PBI_FormatHint = {"isDecimal":true}

	measure Predictability = ```
			
			VAR Calc = DIVIDE([Predictability_Actual_Value], [Predictability_Business_Value])  
			RETURN
			    IF(ISBLANK(Calc), "", Calc)
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 7abbc2a7-860d-42c4-a24e-acf7e0e2ec05

	measure Sales_YTD_AsOfToday_Digital = ```
			
			VAR CurrentMonth = MONTH(TODAY()) 
			VAR CurrentDay = DAY(TODAY())
			VAR CurrentYear = YEAR(TODAY())
			VAR Sales = CALCULATE( 
			    [Sales_Digital], 
			    FILTER( 
			        '_Date_Table',  
			        MONTH('_Date_Table'[Date]) <= CurrentMonth && 
			        DAY('_Date_Table'[Date]) <= CurrentDay &&
			        IF(
			            HASONEVALUE('_Date_Table'[Year]),
			            TRUE(),
			            YEAR('_Date_Table'[Date]) = CurrentYear
			        )
			    )
			) 
			RETURN 
			    IF(ISBLANK(Sales), BLANK(), Sales)
			
			```
		lineageTag: 9f6b867d-0640-4541-ae11-b882ddbbdb1a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_YoY% =
			
			VAR __PREV_YEAR = CALCULATE([Sales], DATEADD('_Date_Table'[Date], -1, YEAR))
			RETURN
				DIVIDE([Sales] - __PREV_YEAR, __PREV_YEAR)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: b8491daa-5d53-437b-b058-8d97b6bd1172

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "YearOverYear",
				  "version": 0
				}

		changedProperty = FormatString

	measure Sales_Digital_YoY% =
			
			VAR __PREV_YEAR = CALCULATE([Sales_Digital], DATEADD('_Date_Table'[Date], -1, YEAR))
			RETURN
				DIVIDE([Sales_Digital] - __PREV_YEAR, __PREV_YEAR)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 3dee03d6-480f-4341-998c-a6130c55d1b1

		extendedProperty MeasureTemplate =
				{
				  "daxTemplateName": "YearOverYear",
				  "version": 0
				}

		changedProperty = FormatString

	measure Text_Previous_PI = "in PI " & FORMAT([PI_Previous], "0")
		lineageTag: 59fbbf72-c900-468f-bc99-a303e8c0e87f

	measure Predictability_Past = ```
			
			VAR CurrentPI = [PI_Current]
			VAR ActualValue = CALCULATE(
			    SUM('Delivery_Details_New'[Actual Value]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3, 
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] < CurrentPI
			    )
			VAR BusinessValue = CALCULATE(
			    SUM('Delivery_Details_New'[Business Value]), 
			    'Delivery_Details_New'[Committed Objective] = TRUE(), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3, 
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] < CurrentPI
			    )
			VAR Predictability = DIVIDE(ActualValue, BusinessValue)
			RETURN
			    Predictability
			
			```
		formatString: 0.00%;-0.00%;0.00%
		lineageTag: 80ddd78b-c459-4729-ad0f-0cbff53b3352

	measure Objective_Count_Committed = ```
			
			CALCULATE(
			    COUNT('Delivery_Details'[Work Item Id]), 
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[Committed Objective] = TRUE()
			    )
			```
		formatString: 0
		lineageTag: 6cc4a4bc-4a95-4801-bc8e-0d5f0c2abd11

	measure Sales_YoY_Pct_Change = ```
			
			VAR CurrentPeriod = 
			    CALCULATE(
			        [Sales],
			        DATESINPERIOD(
			            '_Date_Table'[Date],
			            MAX('_Date_Table'[Date]),
			            -12,
			            MONTH
			        )
			    )
			VAR PreviousPeriod = 
			    CALCULATE(
			        [Sales],
			        DATESINPERIOD(
			            '_Date_Table'[Date],
			            EDATE(MAX('_Date_Table'[Date]), -12),
			            -12,
			            MONTH
			        )
			    )
			RETURN
			    DIVIDE(
			        CurrentPeriod - PreviousPeriod,
			        PreviousPeriod,
			        BLANK()
			    )
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 2ab9a91f-1a92-450f-bd02-c9f5aa5ed53e

	measure Sales_YoY_Pct_Change_Digital = ```
			
			VAR CurrentPeriod = 
			    CALCULATE(
			        [Sales_Digital],
			        DATESINPERIOD(
			            '_Date_Table'[Date],
			            MAX('_Date_Table'[Date]),
			            -12,
			            MONTH
			        )
			    )
			VAR PreviousPeriod = 
			    CALCULATE(
			        [Sales_Digital],
			        DATESINPERIOD(
			            '_Date_Table'[Date],
			            EDATE(MAX('_Date_Table'[Date]), -12),
			            -12,
			            MONTH
			        )
			    )
			RETURN
			    DIVIDE(
			        CurrentPeriod - PreviousPeriod,
			        PreviousPeriod,
			        BLANK()
			    )
			
			```
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 055b2f04-9c15-428f-9551-af0a76cfc9ac

	measure Sales_Compare_Last_Year = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    SAMEPERIODLASTYEAR(
			        DATESBETWEEN(
			            '_Date_Table'[Date],
			            DATE(YEAR(TODAY()), 1, 1),
			            EOMONTH(TODAY(), -1)
			        )
			    )
			)
			
			```
		lineageTag: 309ec638-8079-4e08-9b9c-06f13c5a9a0f

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Current_Period = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    DATESBETWEEN(
			        '_Date_Table'[Date],
			        DATE(YEAR(TODAY()), 1, 1),
			        EOMONTH(TODAY(), -1) // Only calculates full months 
			    )
			)
			
			```
		lineageTag: ad0c4174-cdad-4519-96b8-3876e54f7191

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Pct_Change =
			
			DIVIDE(
			    [Sales_Current_Period] - [Sales_Previous_Period],
			    [Sales_Previous_Period],
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: 29412b8f-5896-4ecc-95ce-39c00b853847

	measure Sales_Previous_Period = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    SAMEPERIODLASTYEAR(
			        DATESBETWEEN(
			            '_Date_Table'[Date],
			            DATE(YEAR(TODAY()), 1, 1),
			            EOMONTH(TODAY(), -1)
			        )
			    )
			)
			
			```
		lineageTag: cb4f973d-5d0d-4445-8e9e-15100de68373

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Current_Period_Digital = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    'F_Shipper_Item'[WEB_ORDERS] = "Web Sales",
			    DATESBETWEEN(
			        '_Date_Table'[Date],
			        DATE(YEAR(TODAY()), 1, 1),
			        EOMONTH(TODAY(), -1)
			    )
			)
			
			```
		lineageTag: 338dee43-23a5-4877-b653-e9e4602699cb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Previous_Period_Digital = ```
			
			CALCULATE(
			    SUM('F_Shipper_Item'[SALES_AMOUNT]),
			    'F_Shipper_Item'[WEB_ORDERS] = "Web Sales",
			    DATESBETWEEN(
			        '_Date_Table'[Date],
			        DATE(YEAR(TODAY()) - 1, 1, 1),
			        EOMONTH(TODAY(), -13)
			    )
			)
			
			```
		lineageTag: d81604c6-64ae-45d0-ae08-8eb8e9011a30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Sales_Pct_Change_Digital =
			
			DIVIDE(
			    [Sales_Current_Period_Digital] - [Sales_Previous_Period_Digital],
			    [Sales_Previous_Period_Digital],
			    0
			)
		formatString: 0.0%;-0.0%;0.0%
		lineageTag: f1db0efb-2890-49c2-b860-82d04b8ba9d8

	measure Sales_Raw =
			
			VAR Calc = SUM('F_Shipper_Item'[SALES_AMOUNT])
			RETURN
			    IF(ISBLANK(Calc), " ", Calc)
		lineageTag: b64c410f-c5e3-4407-9e4f-a0d3f0fb656a

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Costs_Raw =
			
			VAR Calc = SUM('F_Shipper_Item'[TOTAL_CUSTOMER_COST_AMOUNT])
			RETURN
			    IF(ISBLANK(Calc), " ", Calc)
		lineageTag: c678fc77-4974-4d15-bb2c-1361ecf35142

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure Predictability_Previous_Previous = ```
			
			VAR PreviousPI = [PI_Previous_Previous] 
			VAR PredictabilityLastPI = CALCULATE(
			    SUM('APMO_Predictability_COPY_Unpivoted'[Value]),
			    'APMO_Predictability_COPY_Unpivoted'[Attribute] = "ART Predictability Score",
			    'APMO_Predictability_COPY_Unpivoted'[PI] = PreviousPI
			    )
			RETURN
			    IF(ISBLANK(PredictabilityLastPI), "", PredictabilityLastPI)
			```
		lineageTag: e4348fa0-cd8f-444b-be58-039bf3f3fc09

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Objective_Count_At_Risk_Text =
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult =
			    CALCULATE(
			        COUNT('Delivery_Details_New'[Work Item Id]),
			        'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details_New'[Committed Objective] = TRUE(),
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue,
			        'Delivery_Details_New'[Risk] IN {"Red", "Yellow"}
			    )
			RETURN
			    IF(CountResult = 0, " ", "At Risk")
		lineageTag: 9ab23487-6761-41bb-90bf-1e851baffb83

	measure _Objective_Count_Delivered_On_Plan_Uncommitted = ```
			
			VAR CurrentPI = [PI_Current]
			RETURN
			    CALCULATE(
			        COUNT('Delivery_Details_New'[Work Item Id]), 
			        'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] > 3, 
			        'Delivery_Details_New'[PI_Current_Iteration_Path_Int] < CurrentPI,
			        'Delivery_Details_New'[Committed Objective] = FALSE(),
			        'Delivery_Details_New'[State] = "Closed",
			        NOT(CONTAINSSTRING('Delivery_Details_New'[Iteration Path], "Incomplete"))
			    )
			```
		formatString: 0
		lineageTag: be47eaad-4ddb-418d-9479-dc37043aca33

	measure test_Objective_Count_Committed_Current_PI =
			
			VAR CurrentPIValue = [PI_Current]
			VAR CountResult = CALCULATE(
			    COUNT('Delivery_Details_New'[Work Item Id]),
			    'Delivery_Details_New'[Work Item Type] = "Team PI Objective",
			    'Delivery_Details_New'[Committed Objective] = TRUE(),
			    'Delivery_Details_New'[PI_Current_Iteration_Path_Int] = CurrentPIValue
			)
			RETURN
			    IF(ISBLANK(CountResult), "", CountResult)
		lineageTag: e993f5db-8f05-4d02-ad4c-0c66ce8edc66

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure _Blank_Card = " "
		lineageTag: d7b8cb50-7bbb-44a8-9bcb-afdfb7258049

	partition _Measure_Table-8188158d-03d4-437e-a691-07154e8833cf = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

