/// Sum of total Reportable Accidents
table 'Measure Table'
	lineageTag: ce2aa14d-6693-4b71-be30-f49cd138f021

	/// Refresh Date for Loss Run Report
	measure 'Report Refresh Date' = "Report as of: " & Max('zLast Refresh Datetime'[Last Refresh Datetime])
		displayFolder: Metadata
		lineageTag: 2360455c-966c-4ea4-af74-a5137572a971

		changedProperty = IsHidden

	measure 'Current User' = USERPRINCIPALNAME()
		displayFolder: Metadata
		lineageTag: 38fe5af7-087b-48d6-b229-6d8a731e3fbd

	partition 'Measure Table-8188158d-03d4-437e-a691-07154e8833cf' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

