/// Sum of total Reportable Accidents
table 'Measure Table'
	lineageTag: ce2aa14d-6693-4b71-be30-f49cd138f021

	/// Refresh Date for Loss Run Report
	measure 'Report Refresh Date' = "Report as of: " & Max('zLast Refresh Datetime'[Last Refresh Datetime])
		displayFolder: Metadata
		lineageTag: 2360455c-966c-4ea4-af74-a5137572a971

	measure 'Count of Ship-to records' = COUNTROWS(F_Cost_Savings_Ship_To)
		formatString: #,0
		displayFolder: Ship-To Cost Savings
		lineageTag: 83357d20-2d93-4031-9888-e2fb7372106b

	measure 'Actual Price' = Sum(F_Cost_Savings_Details[ACTUAL_PRICE])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Detailed Cost Savings
		lineageTag: f215179b-d0aa-4f61-ab97-93cf0b8fdcac

	measure 'VAS EXT Price' = Sum(F_Cost_Savings_Details[VAS_EXT_PRICE])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Detailed Cost Savings
		lineageTag: edc71a24-d0c6-44f4-b310-8fd6b31551ac

	measure 'Unit Price' = Sum(F_Cost_Savings_Details[VAS_UNIT_PRICE])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Detailed Cost Savings
		lineageTag: 7b21caa6-22d1-4ff9-bec1-d6767a8f340c

	measure 'Unit Quantity' = Sum(F_Cost_Savings_Details[QUANTITY])
		formatString: #,0
		displayFolder: Detailed Cost Savings
		lineageTag: f935ec0a-a6ea-493b-8992-a4a2f6be6ab8

	measure 'Count of rows Details table' = COUNTROWS(F_Cost_Savings_Details)
		formatString: #,0
		displayFolder: Detailed Cost Savings
		lineageTag: c70e35ac-bf84-4c65-a634-6add2f9fb57f

		annotation PBI_FormatHint = {"isDecimal":true}

	measure 'Approved Cost Savings' = Sum(F_Cost_Savings_Ship_To[APPROVED])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Ship-To Cost Savings
		lineageTag: c0cea7a7-7b27-4932-bd8e-9679c6842296

	measure 'Commit on Current Sales' = Sum(F_Cost_Savings_Ship_To[commit_on_cur_sales])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Ship-To Cost Savings
		lineageTag: 1301cc82-7538-4896-8d1c-43a7a8ec7ffc

	measure 'Disapproved Cost Savings' = Sum(F_Cost_Savings_Ship_To[DISAPPROVED])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Ship-To Cost Savings
		lineageTag: c7a204a8-fcb4-47b5-9508-9d15faf5050b

	measure 'Pending Cost Savings' = sum(F_Cost_Savings_Ship_To[PENDING])
		displayFolder: Ship-To Cost Savings
		lineageTag: 83fa3fb7-669a-4769-b114-df49ddf14a43

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Ship-To Sales' = Sum(F_Cost_Savings_Ship_To[SALES])
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		displayFolder: Ship-To Cost Savings
		lineageTag: 90ef04b0-7e49-4f63-b712-1f5b15e9c33c

	partition 'Measure Table-8188158d-03d4-437e-a691-07154e8833cf' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

