table activity_index
	lineageTag: c2e22b9f-376c-4c43-9660-0fb04d8bb243

	column 'User-facing App Id'
		dataType: string
		lineageTag: 89de160d-378c-442a-8350-9dcd1c69fe6a
		summarizeBy: none
		sourceColumn: User-facing App Id

		annotation SummarizationSetBy = Automatic

	column 'Number of Users'
		dataType: int64
		formatString: 0
		lineageTag: 3ee77876-7ab5-4332-97a2-b181c0b859b6
		summarizeBy: sum
		sourceColumn: Number of Users

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column Selections/User
		dataType: double
		lineageTag: 4598c117-f359-4ead-9181-20e443519b35
		summarizeBy: sum
		sourceColumn: Selections/User

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sessions/User
		dataType: double
		lineageTag: 8ffb9213-88b9-4ddd-b77a-fce637a50050
		summarizeBy: sum
		sourceColumn: Sessions/User

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Avg Session Duration'
		dataType: dateTime
		formatString: General Date
		lineageTag: 23e178fd-d026-4bb1-b9a0-8baf19f8bf74
		summarizeBy: none
		sourceColumn: Avg Session Duration

		annotation SummarizationSetBy = Automatic

	column 'User Facing App'
		dataType: string
		lineageTag: d2a23d93-e2c4-4ee5-89fc-f37cdcc8b20d
		summarizeBy: none
		sourceColumn: User Facing App

		annotation SummarizationSetBy = Automatic

	column 'Avg Session Duration - Minutes'
		dataType: double
		lineageTag: 12ace619-acb4-4bb3-b8d0-8feff69db463
		summarizeBy: sum
		sourceColumn: Avg Session Duration - Minutes

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column engagement_unscaled
		dataType: double
		lineageTag: 2cece26e-7e30-40f9-a5f7-32794278c131
		summarizeBy: sum
		sourceColumn: engagement_unscaled

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column activity_index_unscaled
		dataType: double
		lineageTag: baed26d1-50e2-4b11-83e1-aa89a1ecf6ba
		summarizeBy: sum
		sourceColumn: activity_index_unscaled

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column dummy
		dataType: string
		lineageTag: 55bf4684-94b6-4a3b-80d6-0f5c89e4b0cb
		summarizeBy: none
		sourceColumn: dummy

		annotation SummarizationSetBy = Automatic

	column min_engagement
		dataType: double
		lineageTag: 02daf767-3268-48de-96c2-75e9fcd83966
		summarizeBy: sum
		sourceColumn: min_engagement

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_engagement
		dataType: double
		lineageTag: 0a4e5ae2-13c4-44ba-a0ca-3dcea03ed33a
		summarizeBy: sum
		sourceColumn: max_engagement

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column min_activity_index
		dataType: double
		lineageTag: d42ecc89-df69-4a22-98af-fd4dc8fcaefa
		summarizeBy: sum
		sourceColumn: min_activity_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column max_activity_index
		dataType: double
		lineageTag: 8d123b56-8c69-46c1-b2f4-42b902d573b0
		summarizeBy: sum
		sourceColumn: max_activity_index

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column engagement
		dataType: double
		formatString: 0.0000
		lineageTag: 4b4b112c-2283-4516-b47f-be09acaec66e
		summarizeBy: sum
		sourceColumn: engagement

		annotation SummarizationSetBy = Automatic

	column activity_index
		dataType: double
		formatString: 0.00
		lineageTag: 10842e6e-75fa-4756-aa03-538fbf79b58d
		summarizeBy: sum
		sourceColumn: activity_index

		annotation SummarizationSetBy = Automatic

	column 'Total Sessions'
		dataType: int64
		lineageTag: 41b5cf9e-181b-454a-b2cd-434eee8d5b2e
		summarizeBy: sum
		sourceColumn: Total Sessions

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'User-facing App Workspace'
		dataType: string
		lineageTag: fc413007-94c1-4689-b331-9de07d322e43
		summarizeBy: none
		sourceColumn: User-facing App Workspace

		annotation SummarizationSetBy = Automatic

	column export_location
		dataType: string
		lineageTag: bfe681c3-1d52-4bda-80c9-9bdd1bfc2a67
		summarizeBy: none
		sourceColumn: export_location

		annotation SummarizationSetBy = Automatic

	partition activity_index = m
		mode: import
		queryGroup: 'Activity Index Calculations'
		source =
				let
				    Source = Csv.Document(File.Contents(PreloadedFiles & "\activity_index.csv"),[Delimiter=",", Columns=19, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"User-facing App Id", type text}, {"User-facing App Workspace", type text}, {"Number of Users", Int64.Type}, {"Selections/User", type number}, {"Sessions/User", type number}, {"Avg Session Duration", type datetime}, {"User Facing App", type text}, {"Total Sessions", Int64.Type}, {"Avg Session Duration - Minutes", type number}, {"engagement_unscaled", type number}, {"activity_index_unscaled", type number}, {"dummy", type text}, {"min_engagement", type number}, {"max_engagement", type number}, {"min_activity_index", type number}, {"max_activity_index", type number}, {"engagement", type number}, {"activity_index", type number}, {"export_location", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

