table 'Script Lines'
	lineageTag: e1bc30d3-1c6e-4953-9566-8638783cf4cd

	column Id
		dataType: string
		lineageTag: 7b0f07b9-f0e6-4026-8924-59950d0d669c
		summarizeBy: none
		sourceColumn: Id

		annotation SummarizationSetBy = Automatic

	column Page
		dataType: string
		lineageTag: 5a563d79-3a8a-4732-89f2-ba008f22a57b
		summarizeBy: none
		sourceColumn: Page

		annotation SummarizationSetBy = Automatic

	column Lines
		dataType: string
		lineageTag: ae1f66a4-f689-4bd7-bd13-8b7da8c65bd0
		summarizeBy: none
		sourceColumn: Lines

		annotation SummarizationSetBy = Automatic

	column Index
		dataType: int64
		formatString: 0
		lineageTag: de1c32d4-7393-4384-912c-177ee09d74db
		summarizeBy: none
		sourceColumn: Index

		annotation SummarizationSetBy = User

	column 'Solution ID'
		dataType: string
		lineageTag: e6d03bb4-2b72-48d5-adf0-b27afc0d7e65
		summarizeBy: none
		sourceColumn: Solution ID

		annotation SummarizationSetBy = Automatic

	column AppKey
		dataType: string
		lineageTag: 50f3752b-02b2-4b90-88a7-d6b2e016d108
		summarizeBy: none
		sourceColumn: AppKey

		annotation SummarizationSetBy = Automatic

	partition 'Script Lines' = m
		mode: import
		queryGroup: 'Rationalization Dashboard\Tables From Vortex\Script Queries'
		source = ```
				let
				    Source = Sql.Database("zod2ys4pcriu7jy5mie3tmbvou-fwrxbboq5w6ufn7ubv4aw4axhu.datawarehouse.fabric.microsoft.com", "Rationalization"),
				    Navigation = Source{[Schema="dbo",Item="motion_industries_script_lines"]}[Data],
				    #"Renamed Columns" = Table.RenameColumns(Navigation,{{"Solution_ID", "Solution ID"}}),
				    #"Changed Type" = Table.TransformColumnTypes(#"Renamed Columns",{{"Solution ID", type text}, {"Id", type text}, {"Page", type text}, {"Lines", type text}, {"Index", Int64.Type}})
				in 
				    #"Changed Type"
				```

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

