table UsernameConversions
	lineageTag: 889791aa-c7bb-462d-a688-493b623a6366

	column 'User Name'
		dataType: string
		lineageTag: 0510f9e3-c39e-44dc-a801-9035f74422b7
		summarizeBy: none
		sourceColumn: User Name

		annotation SummarizationSetBy = Automatic

	column 'User Id'
		dataType: string
		lineageTag: cdf9b7cf-bcd3-4966-ac3a-13a2bcc996e7
		summarizeBy: none
		sourceColumn: User Id

		annotation SummarizationSetBy = Automatic

	partition UsernameConversions = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents(SupportingFiles & "\zQlikUsernameConversion.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"User Name", type text}, {"User Id", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

