table D_Calendar
	lineageTag: 52d12818-b93f-4045-9616-f86c1d8e8af3

	column CALENDAR_DATE
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: 5c6bf27c-a760-4514-a800-5b8c501f4d12
		summarizeBy: none
		sourceColumn: CALENDAR_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

		annotation PBI_FormatHint = {"isDateTimeCustom":true}

	column YEAR
		dataType: string
		lineageTag: 63524c8f-e513-4878-a987-e01eb341a901
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column QUARTER
		dataType: string
		lineageTag: d7be4cbb-e547-475f-932e-ef4455a9283d
		summarizeBy: none
		sourceColumn: QUARTER

		annotation SummarizationSetBy = Automatic

	column QUARTER_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: a895ab84-75f2-4a26-9cb2-f6b0c71bcb29
		summarizeBy: none
		sourceColumn: QUARTER_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QUARTER_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 79f8b1d4-6c38-43a5-aed8-d71ccf2e65b4
		summarizeBy: none
		sourceColumn: QUARTER_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MONTH_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 2a7fac6f-e7d0-4a10-bb96-4154b5415af0
		summarizeBy: sum
		sourceColumn: MONTH_NUMBER

		annotation SummarizationSetBy = Automatic

	column MONTH_YEAR
		dataType: string
		lineageTag: c0f9f2a0-8601-409a-bd56-962f06c88e71
		summarizeBy: none
		sourceColumn: MONTH_YEAR

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column DAY_OF_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 3918775b-f4a6-4487-b7e8-f65f92ade700
		summarizeBy: sum
		sourceColumn: DAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

	column WEEK
		dataType: string
		lineageTag: 092399f3-b453-4390-b447-05f362ff6f80
		summarizeBy: none
		sourceColumn: WEEK

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: string
		lineageTag: bb5befac-be81-4ca5-ad92-df63f087cb55
		summarizeBy: none
		sourceColumn: MONTH

		annotation SummarizationSetBy = Automatic

	column MONTH_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: cedd0a9b-9306-40ac-a194-2b99ff2651b4
		summarizeBy: none
		sourceColumn: MONTH_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MONTH_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 3fd057ef-5822-4442-aee0-064ec2866966
		summarizeBy: none
		sourceColumn: MONTH_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: ea4c3e56-64cf-42ce-8327-779cd8b97404
		summarizeBy: sum
		sourceColumn: WEEK_NUMBER

		annotation SummarizationSetBy = Automatic

	column WEEK_NUMBER_YEAR
		dataType: string
		lineageTag: 7cc58ffe-245c-40aa-a0c5-2886076211dc
		summarizeBy: none
		sourceColumn: WEEK_NUMBER_YEAR

		annotation SummarizationSetBy = Automatic

	column WEEK_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 332b0635-4be3-4b2a-9926-ec8ffe17c364
		summarizeBy: none
		sourceColumn: WEEK_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 1db9b66c-cb9e-4d7f-86f6-280706b25479
		summarizeBy: none
		sourceColumn: WEEK_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_DAY_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: a4609ac3-c8e5-48be-af7d-c37570d4e044
		summarizeBy: sum
		sourceColumn: WEEK_DAY_NUMBER

		annotation SummarizationSetBy = Automatic

	column WEEK_DAY
		dataType: string
		lineageTag: f07f67e6-6850-4cc7-ac03-8fc792bdcfc0
		summarizeBy: none
		sourceColumn: WEEK_DAY

		annotation SummarizationSetBy = Automatic

	column MTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 44b4b902-0af3-4a79-947c-308a55705d94
		summarizeBy: none
		sourceColumn: MTD_FLAG

		annotation SummarizationSetBy = Automatic

	column QTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: c86427d0-fcf6-4253-8103-1d76dd692d74
		summarizeBy: none
		sourceColumn: QTD_FLAG

		annotation SummarizationSetBy = Automatic

	column YTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7568f6b8-7c48-49b9-897b-7b3201c93f1f
		summarizeBy: none
		sourceColumn: YTD_FLAG

		annotation SummarizationSetBy = Automatic

	column YEAR_QUARTER
		dataType: string
		lineageTag: dd4f07ed-36ba-42ab-86f1-f983e1a4c16c
		summarizeBy: none
		sourceColumn: YEAR_QUARTER

		annotation SummarizationSetBy = Automatic

	column END_OF_MONTH_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 44b793b2-1c84-421b-8240-a04337420268
		summarizeBy: none
		sourceColumn: END_OF_MONTH_FLAG

		annotation SummarizationSetBy = Automatic

	column WORKDAY_OF_MONTH
		dataType: double
		lineageTag: 18b9edd3-da66-4cd8-9d23-8d43efaa83a6
		summarizeBy: sum
		sourceColumn: WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WORKDAY_OF_YEAR
		dataType: double
		lineageTag: 93aadae2-5553-42a4-87d1-afc82133608b
		summarizeBy: sum
		sourceColumn: WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a86b9da4-6e71-4e18-a7ed-2e326c209dfe
		summarizeBy: none
		sourceColumn: WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 65c34e54-d0bc-4973-9119-b5dfddba27d7
		summarizeBy: none
		sourceColumn: HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column BUSINESS_DAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bfa1a9e5-c032-4058-b549-27168ea50138
		summarizeBy: none
		sourceColumn: BUSINESS_DAY_FLAG

		annotation SummarizationSetBy = Automatic

	column CANADA_WORKDAY_OF_MONTH
		dataType: double
		lineageTag: 8672ae36-4957-49a1-8f37-174ba92f90ad
		summarizeBy: sum
		sourceColumn: CANADA_WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CANADA_WORKDAY_OF_YEAR
		dataType: double
		lineageTag: 00cd2a3c-36e9-4e41-9b2d-95905e133a57
		summarizeBy: sum
		sourceColumn: CANADA_WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CANADA_WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: dc71ef57-818f-4957-910e-986cff0193c0
		summarizeBy: none
		sourceColumn: CANADA_WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column CANADA_HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 94db8298-def3-429c-9f58-b97738384958
		summarizeBy: none
		sourceColumn: CANADA_HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column MEXICO_WORKDAY_OF_MONTH
		dataType: double
		lineageTag: 1fb6f0cb-8083-4284-b616-9442916164db
		summarizeBy: sum
		sourceColumn: MEXICO_WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEXICO_WORKDAY_OF_YEAR
		dataType: double
		lineageTag: 7730c1f9-3a38-40ce-a341-f0819fc5764a
		summarizeBy: sum
		sourceColumn: MEXICO_WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEXICO_WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e27a8697-4bfc-44ed-9ddd-2029b7b5d9e3
		summarizeBy: none
		sourceColumn: MEXICO_WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column MEXICO_HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d6b349a8-77f5-40ef-833c-08f54f594ee6
		summarizeBy: none
		sourceColumn: MEXICO_HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column PRIM_KEY_CHKSUM_VAL
		dataType: string
		lineageTag: e99c0f7c-f354-4228-bf53-66dae14e756b
		summarizeBy: none
		sourceColumn: PRIM_KEY_CHKSUM_VAL

		annotation SummarizationSetBy = Automatic

	column CHKSUM_VAL
		dataType: string
		lineageTag: 04d2849d-cf45-401c-978c-425feb1cd08a
		summarizeBy: none
		sourceColumn: CHKSUM_VAL

		annotation SummarizationSetBy = Automatic

	column INS_DT
		dataType: dateTime
		formatString: General Date
		lineageTag: d4aca0ed-d09d-4106-90a1-2a49e27a4955
		summarizeBy: none
		sourceColumn: INS_DT

		annotation SummarizationSetBy = Automatic

	column UPD_DT
		dataType: dateTime
		formatString: General Date
		lineageTag: 96aebb99-91f7-4c69-ad05-9b139dc7048c
		summarizeBy: none
		sourceColumn: UPD_DT

		annotation SummarizationSetBy = Automatic

	column PYTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: d4a62204-440c-4a0d-a444-84d4dfc00dcc
		summarizeBy: none
		sourceColumn: PYTD_FLAG

		annotation SummarizationSetBy = Automatic

	column PPYTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 7ae7beaa-9710-4944-9d04-6017ba2ad436
		summarizeBy: none
		sourceColumn: PPYTD_FLAG

		annotation SummarizationSetBy = Automatic

	column PY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3d492b8a-6ebe-45ee-a86e-a473d251c233
		summarizeBy: none
		sourceColumn: PY_FLAG

		annotation SummarizationSetBy = Automatic

	column PPY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b03cd10e-e808-4451-bb44-9d003681ac24
		summarizeBy: none
		sourceColumn: PPY_FLAG

		annotation SummarizationSetBy = Automatic

	column CY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 9ce60923-9311-4831-8137-af84f3736a97
		summarizeBy: none
		sourceColumn: CY_FLAG

		annotation SummarizationSetBy = Automatic

	column CM_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: a38d1698-7a90-4932-880b-15b9f6ba65c4
		summarizeBy: none
		sourceColumn: CM_FLAG

		annotation SummarizationSetBy = Automatic

	column P24M_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 6e23b5b4-8693-4aef-9195-14b56c9870cf
		summarizeBy: none
		sourceColumn: P24M_FLAG

		annotation SummarizationSetBy = Automatic

	column DAY_OF_YEAR
		dataType: int64
		formatString: 0
		lineageTag: a92b25b8-3158-4e36-bd17-bf3826c97c25
		summarizeBy: sum
		sourceColumn: DAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

	column MONTH_INDEX
		dataType: int64
		formatString: 0
		lineageTag: 8738db68-4d02-49a9-a9fb-17f45f5eccc5
		summarizeBy: sum
		sourceColumn: MONTH_INDEX

		annotation SummarizationSetBy = Automatic

	column QUARTER_INDEX
		dataType: string
		lineageTag: 86a668a7-cb45-48ca-916b-6b2e56f98886
		summarizeBy: none
		sourceColumn: QUARTER_INDEX

		annotation SummarizationSetBy = Automatic

	column DAY_OF_QUARTER
		dataType: int64
		formatString: 0
		lineageTag: b3a6d167-a18c-4c3a-b2f8-534227d0e0d8
		summarizeBy: sum
		sourceColumn: DAY_OF_QUARTER

		annotation SummarizationSetBy = Automatic

	partition D_Calendar = m
		mode: import
		source =
				let
				    Source = Sql.Database("mtlttngl6lvehlaffy3tzayehy-255cr47brb7ubl4dmbam3tblom.datawarehouse.fabric.microsoft.com", "Enterprise_Analytics"),
				    dbo_D_Calendar = Source{[Schema="dbo",Item="D_Calendar"]}[Data],
				    #"Changed Type" = Table.TransformColumnTypes(dbo_D_Calendar,{{"CALENDAR_DATE", type date}}),
				    #"Filtered Rows" = Table.SelectRows(#"Changed Type", each [CALENDAR_DATE] > #date(1994, 1, 4))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

