table D_Manufacturer
	excludeFromModelRefresh
	lineageTag: c81a35ed-046a-488a-8da2-3ac1160b1da8

	column 'Mfr Key'
		dataType: string
		isKey
		lineageTag: ecf253ae-f9fa-41aa-adea-c5c3c76863ec
		summarizeBy: none
		sourceColumn: Mfr Key

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mfr Name'
		dataType: string
		lineageTag: 77b6c789-1415-4ac4-8621-64bc5739e280
		summarizeBy: none
		sourceColumn: Mfr Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Mfr Supplier Inmotion'
		dataType: string
		lineageTag: 7653ca32-1d8c-44d2-99f7-6b8c626f14a2
		summarizeBy: none
		sourceColumn: Mfr Supplier Inmotion

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Enterprise No  Enterprise Name'
		dataType: string
		lineageTag: 2ae3840a-4a6c-414e-91ff-09e885d961e1
		summarizeBy: none
		sourceColumn: Enterprise No  Enterprise Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Enterprise No'
		dataType: string
		lineageTag: 8789b1f0-09cd-4b1d-ae43-395c07ffcf53
		summarizeBy: none
		sourceColumn: Enterprise No

		annotation SummarizationSetBy = Automatic

	column 'Enterprise Name'
		dataType: string
		lineageTag: acfece4a-ed91-489b-a616-9476cdde1a4e
		summarizeBy: none
		sourceColumn: Enterprise Name

		annotation SummarizationSetBy = Automatic

	column 'Mfr Ctl No'
		dataType: string
		lineageTag: efd49499-74c4-41b3-9140-49a55f0b68f0
		summarizeBy: none
		sourceColumn: Mfr Ctl No

		annotation SummarizationSetBy = Automatic

	column 'Mfr Ctl No & Name'
		dataType: string
		lineageTag: 452db09c-b8ba-4287-9e2e-36e355205ec8
		summarizeBy: none
		sourceColumn: Mfr Ctl No & Name

		annotation SummarizationSetBy = Automatic

	column 'Mfr Ctl No  Mfr Name'
		dataType: string
		lineageTag: 8d670588-8520-49b5-8762-a3888103af93
		summarizeBy: none
		sourceColumn: Mfr Ctl No  Mfr Name

		annotation SummarizationSetBy = Automatic

	partition D_Manufacturer = m
		mode: import
		queryGroup: Dimensions
		source = ```
				let
				    Source = Sql.Database(Lakehouse&".datawarehouse.fabric.microsoft.com", "Enterprise_Analytics"),
				    dbo_D_Manufacturer = Value.NativeQuery(Source, 
				    "SELECT MFR.* 
				    FROM dbo.D_Manufacturer MFR 
				    INNER JOIN (SELECT DISTINCT MFR_KEY FROM dbo.F_Order_Item) ORD
				        ON ORD.MFR_KEY = MFR.MFR_KEY", null, [EnableFolding = true]),
				    #"Removed Other Columns" = Table.SelectColumns(dbo_D_Manufacturer,{"MFR_KEY", "ENTERPRISE_NO", "ENTERPRISE_NAME", "MFR_CTL_NO", "MFR_NAME", "MFR_SUPPLIER_INMOTION", "MFR_CTL_NO__MFR_NAME", "ENTERPRISE_NO__ENTERPRISE_NAME"}),
				    #"Added Custom" = Table.AddColumn(#"Removed Other Columns", "MFR_CTL_NO & NAME", each [MFR_CTL_NO]&"|"&[MFR_NAME]),
				    #"TEMP DEV STEP: LimitRecords" = fx_ConditionallyLimitRows(#"Added Custom", LimitRecordCount, RecordCountLimit),
				    #"Bulk Column Rename" = Table.TransformColumnNames(#"TEMP DEV STEP: LimitRecords", each Text.Combine(List.ReplaceMatchingItems(List.Transform(Text.Split(_,"_"), Text.Proper),{{"Id","ID"}, {"Mi", "MI"}, {"Upn", "UPN"}, {"Usd", "USD"}})," "))
				in
				    #"Bulk Column Rename"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Exception

