table z_Time_Series_Measure_Selector
	lineageTag: e0ab1146-4d56-4c9b-b14b-26e2db7bc368

	column 'Measure Index'
		dataType: int64
		formatString: 0
		lineageTag: db820d5c-bd80-4bd0-8166-27c1fa71adbb
		summarizeBy: none
		sourceColumn: Measure Index

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	column 'Measure Name'
		dataType: string
		lineageTag: 42dbfc61-3e3f-47b5-bcf0-4a6045e191a4
		summarizeBy: none
		sourceColumn: Measure Name

		changedProperty = IsHidden

		annotation SummarizationSetBy = Automatic

	partition z_Time_Series_Measure_Selector = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUXIsS9dTcEnMzKlU8C9KSS0qVorViVYyAsqE5Jck5ig45uaX5pWABU3ggs5wMVOgmH9Bah5EM7JqM6CMe4CCqlJsLAA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Measure Index" = _t, #"Measure Name" = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Measure Index", Int64.Type}, {"Measure Name", type text}})
				in
				    #"Changed Type"

	changedProperty = IsHidden

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

