/// Sum of total Reportable Accidents
table 'Measure Table'
	lineageTag: ce2aa14d-6693-4b71-be30-f49cd138f021

	/// Refresh Date for Loss Run Report
	measure 'Report Refresh Date' = "Report as of: " & Max('zLast Refresh Datetime'[Last Refresh Datetime])
		displayFolder: Metadata
		lineageTag: 2360455c-966c-4ea4-af74-a5137572a971

	measure 'Shipper CTL No' = DISTINCTCOUNT(F_P21_Shipper_Header[SHIPPER_CTL_NO])
		formatString: 0
		lineageTag: ef97f19b-3804-4b52-b355-811d9d8c1d6c

	measure 'MDSE Order Price' = sumx(F_P21_Orders_Line,[ITM_OP_QTY_ORDERED]*[ITM_UNIT_SELL_PRICE])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 903f45d3-e317-4e5d-a49f-601419ea7107

	measure 'MDSE Order Cost' = SUMX(F_P21_Orders_Line, [ITM_UNIT_COST]*[ITM_OP_QTY_ORDERED])
		formatString: \$#,0.00;(\$#,0.00);\$#,0.00
		lineageTag: 47d60411-e224-497e-8011-fb277f232da7

	partition 'Measure Table-8188158d-03d4-437e-a691-07154e8833cf' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Exception

	annotation PBI_NavigationStepName = Navigation

