table 'Data Analytics Child'
	lineageTag: 903f8533-8a5a-4306-a3b7-304cb95a01c5

	measure 'Buffer Story Points' =
			DIVIDE(CALCULATE(
			    SUM('Data Analytics Child'[Story Points]),
			    FILTER(
			        'Data Analytics Parent',
			        'Data Analytics Parent'[Title] = "Data Analytics 2024 Enhancements" ||
			        'Data Analytics Parent'[Title] = "Data Analytics 2024 Support" ||
			        'Data Analytics Parent'[Title] = "Data Analytics 2024 Technical Enablement"
			    )
			),
			DISTINCTCOUNT('Data Analytics Child'[Iteration Path]))
		lineageTag: 662db7e1-995c-4fee-bbab-2c8a80da8aff

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Area Path'
		dataType: string
		lineageTag: 6bf8a7d0-8797-4002-b757-0e2472cad34b
		summarizeBy: none
		sourceColumn: Area Path

		annotation SummarizationSetBy = Automatic

	column 'Assigned To'
		dataType: string
		lineageTag: fed72aa1-5fef-43bf-a8b7-1ae4653e1a64
		summarizeBy: none
		sourceColumn: Assigned To

		annotation SummarizationSetBy = Automatic

	column 'Iteration Path'
		dataType: string
		lineageTag: 4d9b0579-a7a8-48cf-97d1-73e8ed82721f
		summarizeBy: none
		sourceColumn: Iteration Path

		annotation SummarizationSetBy = Automatic

	column 'Created By'
		dataType: string
		lineageTag: eb61b39f-8456-4332-9c9f-38fd0fbafd99
		summarizeBy: none
		sourceColumn: Created By

		annotation SummarizationSetBy = Automatic

	column 'Closed By'
		dataType: string
		lineageTag: 20701e4f-bc18-4ade-90f5-7649ff0a9402
		summarizeBy: none
		sourceColumn: Closed By

		annotation SummarizationSetBy = Automatic

	column 'Work Item Id'
		dataType: int64
		lineageTag: 67e518e9-260f-4f9c-b2d3-114e7daf2f27
		summarizeBy: none
		sourceColumn: Work Item Id

		annotation SummarizationSetBy = User

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Title
		dataType: string
		lineageTag: 1c03e28a-9409-4a95-bae5-0813d2e93bcc
		summarizeBy: none
		sourceColumn: Title

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: 3af2370e-df68-4603-a2c8-03d9cf9e92a7
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Work Item Type'
		dataType: string
		lineageTag: cf70ff84-1c9d-4453-8d0d-2a42d84b176c
		summarizeBy: none
		sourceColumn: Work Item Type

		annotation SummarizationSetBy = Automatic

	column 'Parent Work Item Id'
		dataType: int64
		formatString: 0
		lineageTag: f6cffa25-3453-4e78-a515-ed388225e4bc
		summarizeBy: none
		sourceColumn: Parent Work Item Id

		annotation SummarizationSetBy = Automatic

	column 'Completed Effort'
		dataType: int64
		formatString: 0
		lineageTag: 9dcb5a69-b089-46a0-950e-54b4edb4550f
		summarizeBy: sum
		sourceColumn: Completed Effort

		annotation SummarizationSetBy = Automatic

	column 'Original Estimate'
		dataType: double
		lineageTag: 39ebf42d-c8a6-4120-8c55-731fa7d9387c
		summarizeBy: sum
		sourceColumn: Original Estimate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Expense Type'
		dataType: string
		lineageTag: 136cc8a6-76c2-4415-9782-d312cfeaced5
		summarizeBy: none
		sourceColumn: Expense Type

		annotation SummarizationSetBy = Automatic

	column 'Closed Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: d5a827cb-ede7-4132-ac75-248411b0bb7b
		summarizeBy: none
		sourceColumn: Closed Date

		annotation SummarizationSetBy = Automatic

	column Tags
		dataType: string
		lineageTag: d70d2856-e5c8-4753-bc72-147c2ffb3440
		summarizeBy: none
		sourceColumn: Tags

		annotation SummarizationSetBy = Automatic

	column 'Story Points'
		dataType: double
		formatString: 0
		lineageTag: 1d5a074a-f4fb-48ed-9401-c9ddf19b9b71
		summarizeBy: sum
		sourceColumn: Story Points

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isDecimal":true}

	column 'Requested By'
		dataType: string
		lineageTag: 2778d3dd-956c-4eb8-a455-9bc4b872e660
		summarizeBy: none
		sourceColumn: Requested By

		annotation SummarizationSetBy = Automatic

	column 'Created Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 714c94b3-af3b-4cc8-8a40-d0d4627c7669
		summarizeBy: none
		sourceColumn: Created Date

		annotation SummarizationSetBy = Automatic

	column 'Path_Assignee [Tasks]'
		dataType: string
		lineageTag: 2a9913ae-6d5d-407f-a3f3-becf002c28cf
		summarizeBy: none
		sourceColumn: Path_Assignee [Tasks]

		annotation SummarizationSetBy = Automatic

	column '# of Days Created-to-Close' = DATEDIFF('Data Analytics Child'[Created Date],'Data Analytics Child'[Closed Date],DAY)
		formatString: 0
		lineageTag: 7fa0019f-3277-424b-bf0e-4adfbe23dfa0
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	column 'Activated Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: c733cb9c-3237-4d91-9ec6-8a470a070a00
		summarizeBy: none
		sourceColumn: Activated Date

		annotation SummarizationSetBy = Automatic

	column 'Actual Start'
		dataType: dateTime
		formatString: General Date
		lineageTag: f81224e5-c31f-47fc-ab3c-778dbffb4bb8
		summarizeBy: none
		sourceColumn: Actual Start

		annotation SummarizationSetBy = Automatic

	column 'Actual End'
		dataType: dateTime
		formatString: General Date
		lineageTag: 7dba77c7-5a26-4c82-b9e1-ce7293862863
		summarizeBy: none
		sourceColumn: Actual End

		annotation SummarizationSetBy = Automatic

	column 'InProgress Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 251555dc-3f23-446b-85b2-2b47ee152b3b
		summarizeBy: none
		sourceColumn: InProgress Date

		annotation SummarizationSetBy = Automatic

	column 'State Change Date'
		dataType: dateTime
		formatString: General Date
		lineageTag: 245cfff6-0853-424b-9f4e-b82dedb54d33
		summarizeBy: none
		sourceColumn: State Change Date

		annotation SummarizationSetBy = Automatic

	column '# of Days Start-to-Close' = DATEDIFF('Data Analytics Child'[InProgress Date],'Data Analytics Child'[Closed Date],DAY)
		formatString: 0
		lineageTag: 118b0571-8a77-4c75-b82f-760f314148a1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

	partition 'Data Analytics Child' = m
		mode: import
		source =
				let
				    Source = VSTS.AnalyticsViews("Motion-IT", "MI-Dev", []),
				    #"Shared Views_Folder" = Source{[Id="Shared Views",Kind="Folder"]}[Data],
				    #"2eb3da31-f1a6-4d15-852b-51ce30dd414f_Table" = #"Shared Views_Folder"{[Id="2eb3da31-f1a6-4d15-852b-51ce30dd414f",Kind="Table"]}[Data],
				    #"Added Custom" = Table.AddColumn(#"2eb3da31-f1a6-4d15-852b-51ce30dd414f_Table", "Path_Assignee [Tasks]", each [Iteration Path] & "-" & [Assigned To])
				in
				    #"Added Custom"

	annotation PBI_ResultType = Table

