/// Sum of total Reportable Accidents
table 'Measure Table'
	lineageTag: ce2aa14d-6693-4b71-be30-f49cd138f021

	/// Refresh Date for Loss Run Report
	measure 'Report Refresh Date' = "Report as of: " & Max('zLast Refresh Datetime'[Last Refresh Datetime])
		displayFolder: Metadata
		lineageTag: 2360455c-966c-4ea4-af74-a5137572a971

	measure '# of Work Items' = Count('Data Analytics Child'[Work Item Id])
		formatString: 0
		lineageTag: 9ef4dff7-201c-45e2-b720-bd4391d9227e

	measure Velocity = Sum('Data Analytics Child'[Story Points])/DISTINCTCOUNT('Data Analytics Child'[Iteration Path])
		lineageTag: 59c44f6b-efa6-4044-8b90-ad2dcc09edd9

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Count of Iteration' = DISTINCTCOUNT('Data Analytics Child'[Iteration Path])
		formatString: 0
		lineageTag: cfbf6c7e-1ae6-4f13-9fd7-1130da3d3149

	measure '# of Days Open-to-Close' = SUM('Data Analytics Child'[# of Days Created-to-Close])/COUNTROWS('Data Analytics Child')
		lineageTag: 0c8e1516-ff38-43c3-8e14-e913e350cd62

	measure '# of Days Start-to-Close' = SUM('Data Analytics Child'[# of Days Start-to-Close])/COUNTROWS('Data Analytics Child')
		lineageTag: 2d57b697-00f4-4d6f-be78-d62986136c6b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition 'Measure Table-8188158d-03d4-437e-a691-07154e8833cf' = m
		mode: import
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [Column1 = _t]),
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Column1"})
				in
				    #"Removed Columns"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

