table D_Calendar
	lineageTag: 9aeae863-516e-43bd-abdf-de34cde475b5

	measure rowcount = COUNTROWS('GL_ou_tree')
		formatString: 0
		lineageTag: 75d589f2-e9a0-43dd-8c37-161f15d1c059

	column CALENDAR_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: ee63dbba-e291-4515-a2ec-8809c5412a43
		summarizeBy: none
		sourceColumn: CALENDAR_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column YEAR_QUARTER
		dataType: string
		lineageTag: f3d8ce71-90aa-4930-9d4e-d9dd0308fd44
		summarizeBy: none
		sourceColumn: YEAR_QUARTER

		annotation SummarizationSetBy = Automatic

	column QUARTER_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 6765532f-1fcc-4dcc-ae64-b02234bbf15a
		summarizeBy: none
		sourceColumn: QUARTER_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column QUARTER_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 4ef96190-16f7-47b6-ac5e-8fe9303786c5
		summarizeBy: none
		sourceColumn: QUARTER_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MONTH_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 38eea7d3-2097-4cca-a277-ead3661a3a9d
		summarizeBy: sum
		sourceColumn: MONTH_NUMBER

		annotation SummarizationSetBy = Automatic

	column MONTH_YEAR
		dataType: string
		lineageTag: ab367e80-d01f-41c8-89ff-70f97dddf923
		summarizeBy: none
		sourceColumn: MONTH_YEAR

		annotation SummarizationSetBy = Automatic

	column DAY_OF_MONTH
		dataType: int64
		formatString: 0
		lineageTag: 8eb12801-49bf-45a9-93ca-90f305c4aadb
		summarizeBy: sum
		sourceColumn: DAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

	column WEEK
		dataType: string
		lineageTag: 2df01ab3-bcea-4f96-b45a-e6163ec97c53
		summarizeBy: none
		sourceColumn: WEEK

		annotation SummarizationSetBy = Automatic

	column MONTH
		dataType: string
		lineageTag: ecbb64b6-bdb3-4e6f-a77f-b803869cd519
		summarizeBy: none
		sourceColumn: MONTH
		sortByColumn: MONTH_NUMBER

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

	column YEAR
		dataType: string
		lineageTag: 93cc5569-1401-4816-9f92-d146da766174
		summarizeBy: none
		sourceColumn: YEAR

		annotation SummarizationSetBy = Automatic

	column QUARTER
		dataType: string
		lineageTag: c4e3bde8-d5a4-4317-a04c-1ed72bf9c381
		summarizeBy: none
		sourceColumn: QUARTER

		annotation SummarizationSetBy = Automatic

	column MTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 26abd8d5-b2f2-434e-b315-4df133b778a6
		summarizeBy: none
		sourceColumn: MTD_FLAG

		annotation SummarizationSetBy = Automatic

	column QTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: aabf6d23-2d70-4432-9401-7cad80204dc4
		summarizeBy: none
		sourceColumn: QTD_FLAG

		annotation SummarizationSetBy = Automatic

	column YTD_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: ad2c5143-f3eb-4706-af3d-4115fbff70aa
		summarizeBy: none
		sourceColumn: YTD_FLAG

		annotation SummarizationSetBy = Automatic

	column MONTH_START_DATE
		dataType: dateTime
		formatString: Short Date
		lineageTag: 08d64fa1-60f1-45fb-8291-1a0e63d0535f
		summarizeBy: none
		sourceColumn: MONTH_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column MONTH_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: c27532b5-33b1-4a67-97d0-0d6a58ac231e
		summarizeBy: none
		sourceColumn: MONTH_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_START_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: 2d53b9c1-47ac-46bd-a341-109e135e99c2
		summarizeBy: none
		sourceColumn: WEEK_START_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_DAY
		dataType: string
		lineageTag: 74918dfb-bff2-4b50-8c2d-100ecfe26f5f
		summarizeBy: none
		sourceColumn: WEEK_DAY

		annotation SummarizationSetBy = Automatic

	column WEEK_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 561504ef-f599-4ef7-b39c-1781d9a05434
		summarizeBy: sum
		sourceColumn: WEEK_NUMBER

		annotation SummarizationSetBy = Automatic

	column WEEK_NUMBER_YEAR
		dataType: string
		lineageTag: d526f394-a519-4bac-8728-e77a3cb21769
		summarizeBy: none
		sourceColumn: WEEK_NUMBER_YEAR

		annotation SummarizationSetBy = Automatic

	column WEEK_END_DATE
		dataType: dateTime
		formatString: Long Date
		lineageTag: ac419549-4982-4430-86a6-4268095403a8
		summarizeBy: none
		sourceColumn: WEEK_END_DATE

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column WEEK_DAY_NUMBER
		dataType: int64
		formatString: 0
		lineageTag: 0f407fb0-b95b-4276-a5a3-f2917be2a459
		summarizeBy: sum
		sourceColumn: WEEK_DAY_NUMBER

		annotation SummarizationSetBy = Automatic

	column END_OF_MONTH_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 09f90541-92f1-4287-9145-9ab96c610601
		summarizeBy: none
		sourceColumn: END_OF_MONTH_FLAG

		annotation SummarizationSetBy = Automatic

	column WORKDAY_OF_MONTH
		dataType: double
		lineageTag: 8f8c59d7-f397-4962-af95-59e613f6c33a
		summarizeBy: sum
		sourceColumn: WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WORKDAY_OF_YEAR
		dataType: double
		lineageTag: 45312ceb-e419-4001-a9ef-3c8e58d20694
		summarizeBy: sum
		sourceColumn: WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 3e83cb17-ba40-482c-9a85-148ccabf7ae2
		summarizeBy: none
		sourceColumn: WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 84d5afb7-f569-4920-884e-c969216a439e
		summarizeBy: none
		sourceColumn: HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column BUSINESS_DAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0718a946-8976-4315-b6e6-859beaf26f0b
		summarizeBy: none
		sourceColumn: BUSINESS_DAY_FLAG

		annotation SummarizationSetBy = Automatic

	column CANADA_WORKDAY_OF_MONTH
		dataType: double
		lineageTag: d2c0c1f6-f60c-4232-925d-4710aaabdea3
		summarizeBy: sum
		sourceColumn: CANADA_WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CANADA_WORKDAY_OF_YEAR
		dataType: double
		lineageTag: c7a47baa-f54b-4f69-b66c-444be048cd9d
		summarizeBy: sum
		sourceColumn: CANADA_WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CANADA_WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0e8e8e43-7f76-44d3-9e24-c1eb5e81a82e
		summarizeBy: none
		sourceColumn: CANADA_WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column CANADA_HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: b7e9b21d-8084-42e0-99bf-b0dd92ffcb91
		summarizeBy: none
		sourceColumn: CANADA_HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column MEXICO_WORKDAY_OF_MONTH
		dataType: double
		lineageTag: fbdb928d-72c6-4c63-8c94-6bb154437d75
		summarizeBy: sum
		sourceColumn: MEXICO_WORKDAY_OF_MONTH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEXICO_WORKDAY_OF_YEAR
		dataType: double
		lineageTag: fde4722c-661d-4a96-8fc1-180a8e1ebf18
		summarizeBy: sum
		sourceColumn: MEXICO_WORKDAY_OF_YEAR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column MEXICO_WEEKEND_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 361b1048-cea1-43ff-bad1-167576148cf4
		summarizeBy: none
		sourceColumn: MEXICO_WEEKEND_FLAG

		annotation SummarizationSetBy = Automatic

	column MEXICO_HOLIDAY_FLAG
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: edfff69e-d1df-4af6-b029-321bef37119f
		summarizeBy: none
		sourceColumn: MEXICO_HOLIDAY_FLAG

		annotation SummarizationSetBy = Automatic

	column PRIM_KEY_CHKSUM_VAL
		dataType: string
		lineageTag: 80649af3-e68e-4555-9d8f-396928d3f59c
		summarizeBy: none
		sourceColumn: PRIM_KEY_CHKSUM_VAL

		annotation SummarizationSetBy = Automatic

	column CHKSUM_VAL
		dataType: string
		lineageTag: d58a0a67-01f6-4586-bd9f-d26a75073557
		summarizeBy: none
		sourceColumn: CHKSUM_VAL

		annotation SummarizationSetBy = Automatic

	column INS_DT
		dataType: dateTime
		formatString: General Date
		lineageTag: 90a62264-df23-43fe-b4b6-d01ca5d6fdad
		summarizeBy: none
		sourceColumn: INS_DT

		annotation SummarizationSetBy = Automatic

	column UPD_DT
		dataType: dateTime
		formatString: General Date
		lineageTag: 7e9cdbd4-d759-40c6-b653-ee191cc409cd
		summarizeBy: none
		sourceColumn: UPD_DT

		annotation SummarizationSetBy = Automatic

	partition D_Calendar = m
		mode: import
		source =
				let
				    Source = Sql.Database("mtlttngl6lvehlaffy3tzayehy-255cr47brb7ubl4dmbam3tblom.datawarehouse.fabric.microsoft.com", "Enterprise_Analytics"),
				    dbo_D_Calendar = Source{[Schema="dbo",Item="D_Calendar"]}[Data],
				    #"Filtered Rows" = Table.SelectRows(dbo_D_Calendar, each ([YEAR] = "2020" or [YEAR] = "2021" or [YEAR] = "2022" or [YEAR] = "2023" or [YEAR] = "2024"))
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

